'use strict';

// console.log('JS file is linked');

// JUSTIN WHITAKER

//Uncomment below line if needed
// var allTheThings = [];
var totalVotes = 0;



var BusMallThing = function (name, url) {
  this.name = name;
  this.url = url;
  this.viewTotal = 0;
  this.voteTotal = 0;
  BusMallThing.allTheThings.push(this);
};

var mallPic1 = document.getElementById('image1');
var mallPic2 = document.getElementById('image2');
var mallPic3 = document.getElementById('image3');

// mallPic1.addEventListener('click', function(event) {
//   totalVotes ++;
//   // this.viewTotal ++;
// });

// mallPic2.addEventListener('click', function(event) {
//   totalVotes ++;
// });


//Create all the items in the catalog

function thingsGen() {
new BusMallThing('R2D2 Roller Bag', 'img/01_bag.jpg');
new BusMallThing('Banana slicer', 'img/02_banana.jpg');
new BusMallThing('Bathroom Buddy', 'img/03_bathroom.jpg');
new BusMallThing('Rainy Day Sandals', 'img/04_boots.jpg');
new BusMallThing('Breakfast Maker', 'img/05_breakfast.jpg');
new BusMallThing('Meatball Bubblegum', 'img/06_bubblegum.jpg');
new BusMallThing('Yoga Chair','img/07_chair.jpg');
new BusMallThing('Cthulhu','img/08_cthulhu.jpg');
new BusMallThing('Dog Duckifier','img/09_dog-duck.jpg');
new BusMallThing('Canned Dragon Meat','img/10_dragon.jpg');
new BusMallThing('U-pensils','img/11_pen.jpg');
new BusMallThing('Dog-O-Sweep','img/12_pet-sweep.jpg');
new BusMallThing('Pie Slicer','img/13_scissors.jpg');
new BusMallThing('Sleeping Shark','img/14_shark.jpg');
new BusMallThing('Kid-O-Sweep','img/15_sweep.jpg');
new BusMallThing('Tauntaun Sack','img/16_tauntaun.jpg');
new BusMallThing('Canned Unicorn Meat','img/17_unicorn-meat.jpg');
new BusMallThing('USB Tentacle','img/18_usb-tentacle.jpg');
new BusMallThing('Perpetual Watering Can','img/19_water-can.jpg');
new BusMallThing('Low-Spill Wine Glass','img/20_wine-glass.jpg');
}
thingsGen();

// Keep track of previously displayed things
BusMallThing.lastDisplayed = [];

// Array to store Things generated by constructor
BusMallThing.allTheThings = [];


//respond to clicks
BusMallThing.handleclick = function (event) {

};

// List of results

BusMallThing.showReults = function() {

};

// Data for chart
BusMallThing.updateVotes = function() {

};

//Create chart with Chart.JS
BusMallThing.renderChart = function() {

};

// Select a random image to be displayed
BusMallThing.randomThing = function () {
  var threeUniqueNums = [];
  // Math.random to generate 3 numbers
  while(threeUniqueNums.length < 3) {
    var randNum = Math.floor(Math.random() * allTheThings.length);
//Compare numbers to each other
    if(!BusMallThing.lastDisplayed.includes(randNum) && !threeUniqueNums.includes(randNum)) {
      threeUniqueNums.push(randNum);
    } else {
      console.log('Duplicate number!')
//Compare to previously generated things
//Account for array length of allTheThings

      return threeUniqueNums;
    }
  }
};

// Make 3 numbers to use to select items
// BusMallThing.threeUniqueNums = function() {

// };

// function randomStuff() {
//   return Math.floor(Math.random() * allTheThings.length);
// }
