'use strict';

// console.log('JS file is linked');

// JUSTIN WHITAKER

//Uncomment below line if needed
// var allTheThings = [];
var totalVotes = 0;
var mallPic1 = document.getElementById('image1');
var mallPic2 = document.getElementById('image2');
var mallPic3 = document.getElementById('image3');
// var image1element = Document.getElementsByTagName('img')[0];
// var image2element = Document.getElementsByTagName('img')[1];
// var image3element = Document.getElementsByTagName('img')[2];
// var thing1 = BusMallThing.allTheThings[0];
// var thing1 = BusMallThing.allTheThings[1];

// Array to store Things generated by constructor
BusMallThing.allTheThings = [];

function BusMallThing(name, url) {
  this.name = name,
  this.url = url,
  //How many times has this been viewed?
  this.viewTotal = 0,
  //How many times has this been voted for?
  this.voteTotal = 0,
  BusMallThing.allTheThings.push(this);
}

//Create all the items in the catalog

function thingsGen() {
  new BusMallThing('R2D2 Roller Bag', 'img/01_bag.jpg');
  new BusMallThing('Banana slicer', 'img/02_banana.jpg');
  new BusMallThing('Bathroom Buddy', 'img/03_bathroom.jpg');
  new BusMallThing('Rainy Day Sandals', 'img/04_boots.jpg');
  new BusMallThing('Breakfast Maker', 'img/05_breakfast.jpg');
  new BusMallThing('Meatball Bubblegum', 'img/06_bubblegum.jpg');
  new BusMallThing('Yoga Chair','img/07_chair.jpg');
  new BusMallThing('Cthulhu','img/08_cthulhu.jpg');
  new BusMallThing('Dog Duckifier','img/09_dog-duck.jpg');
  new BusMallThing('Canned Dragon Meat','img/10_dragon.jpg');
  new BusMallThing('U-pensils','img/11_pen.jpg');
  new BusMallThing('Dog-O-Sweep','img/12_pet-sweep.jpg');
  new BusMallThing('Pie Slicer','img/13_scissors.jpg');
  new BusMallThing('Sleeping Shark','img/14_shark.jpg');
  new BusMallThing('Kid-O-Sweep','img/15_sweep.png');
  new BusMallThing('Tauntaun Sack','img/16_tauntaun.jpg');
  new BusMallThing('Canned Unicorn Meat','img/17_unicorn-meat.jpg');
  new BusMallThing('USB Tentacle','img/18_usb-tentacle.jpg');
  new BusMallThing('Perpetual Watering Can','img/19_water-can.jpg');
  new BusMallThing('Low-Spill Wine Glass','img/20_wine-glass.jpg');
}
thingsGen();

// Keep track of previously displayed things
BusMallThing.lastDisplayed = [];

// // List of results

// BusMallThing.showResults = function() {

// };

// // Data for chart
// BusMallThing.updateVotes = function() {

// };

// //Create chart with Chart.JS
// BusMallThing.renderChart = function() {

// };

// Select a random image to be displayed
BusMallThing.threeUniqueNums = function() {
  var threeUniqueArray = [];
  // Math.random to generate 3 numbers
  while(threeUniqueArray.length < 3) {
    var randNum = Math.floor(Math.random() * BusMallThing.allTheThings.length);
    //Compare numbers to each other
    if(!BusMallThing.lastDisplayed.includes(randNum) && !threeUniqueArray.includes(randNum)) {
      threeUniqueArray.push(randNum);
    } else {
      // console.log('Duplicate number!');
      //Compare to previously generated things
      //Account for array length of allTheThings

    }
  }
  BusMallThing.lastDisplayed = threeUniqueArray;
  return threeUniqueArray;
};


BusMallThing.showRandomThing = function() {
  var uniqueIndicesArray = BusMallThing.threeUniqueNums();

  //Increment number of times displayed
  BusMallThing.allTheThings[uniqueIndicesArray[0]].viewTotal++;
  BusMallThing.allTheThings[uniqueIndicesArray[1]].viewTotal++;
  BusMallThing.allTheThings[uniqueIndicesArray[2]].viewTotal++;
  // console.log(BusMallThing.allTheThings[uniqueIndicesArray[0]]);
  // console.log(BusMallThing.allTheThings[uniqueIndicesArray[0]].viewTotal);
  //Display two unique images on the screen
  mallPic1.src = BusMallThing.allTheThings[uniqueIndicesArray[0]].url;
  mallPic1.alt = BusMallThing.allTheThings[uniqueIndicesArray[0]].name;

  mallPic2.src = BusMallThing.allTheThings[uniqueIndicesArray[1]].url;
  mallPic2.alt = BusMallThing.allTheThings[uniqueIndicesArray[1]].name;

  mallPic3.src = BusMallThing.allTheThings[uniqueIndicesArray[2]].url;
  mallPic3.alt = BusMallThing.allTheThings[uniqueIndicesArray[2]].name;
};

BusMallThing.handleClick = function(event) {
  totalVotes ++;
  for (var i in BusMallThing.allTheThings) {
    if (event.target.alt === BusMallThing.allTheThings[i].name)
      BusMallThing.allTheThings[i].voteTotal ++;

  }
  if (totalVotes === 25) {
    mallPic1.removeEventListener('click', BusMallThing.handleClick);
    mallPic2.removeEventListener('click', BusMallThing.handleClick);
    mallPic3.removeEventListener('click', BusMallThing.handleClick);
  }
  BusMallThing.showRandomThing();
};

mallPic1.addEventListener('click', BusMallThing.handleClick);
mallPic2.addEventListener('click', BusMallThing.handleClick);
mallPic3.addEventListener('click', BusMallThing.handleClick);


BusMallThing.showRandomThing();

